services:
  cmsshared:
    image: cmsshared
    build:
      context: shared
      dockerfile: ./Dockerfile
    profiles:
      - build-only
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
