FROM node:20-alpine AS deps

WORKDIR /app

COPY package*.json ./
COPY server/package*.json ./server/
COPY client/package*.json ./client/
COPY shared/package*.json ./shared/

RUN npm ci

COPY . .

FROM node:20-alpine AS runtime

WORKDIR /app

ENV NODE_ENV=production

COPY --from=deps /app /app

EXPOSE 5000

CMD ["npm", "run", "start", "--workspace=server"]
