FROM node:20-alpine AS deps

WORKDIR /app

COPY package*.json ./
COPY server/package*.json ./server/
COPY shared/package*.json ./shared/

RUN npm ci --ignore-scripts --workspace=shared --workspace=server --include-workspace-root=false

COPY server ./server
COPY shared ./shared

FROM node:20-alpine AS runtime

WORKDIR /app

ENV NODE_ENV=production

COPY --from=deps /app /app

RUN chown -R node:node /app

USER node

EXPOSE 5000

CMD ["npm", "run", "start", "--workspace=server"]
