version: "2"
# Authtoken can be provided via NGROK_AUTHTOKEN environment variable or replaced here
authtoken: ""

tunnels:
  cms_client:
    proto: http
    addr: client:43211
    inspect: true
    bind_tls: true
  cms_server:
    proto: http
    addr: server:43210
    inspect: true
    bind_tls: true
