/**
 * Sanitizes a single cell value to prevent CSV Dynamic Data Exchange (DDE) formula injection.
 * Any value beginning with '=', '+', '-', '@', '\t', or '\r' is prefixed with an apostrophe.
 */
export function sanitizeDDE(value) {
  if (value === null || value === undefined) return '';
  const str = String(value).trim();
  if (/^[=+\-@\t\r]/.test(str)) {
    return `'${str}`;
  }
  return str;
}

/**
 * Escapes a cell value for standard RFC 4180 CSV compliance.
 */
export function escapeCSVCell(value) {
  const sanitized = sanitizeDDE(value);
  // Double any existing double-quotes
  const escaped = sanitized.replace(/"/g, '""');
  return `"${escaped}"`;
}

/**
 * Exports capstone records and analytics summary to an enterprise CSV file.
 * Includes an institutional audit metadata header block followed by the structured table data.
 *
 * @param {Array<Object>} records - Array of capstone report records.
 * @param {Object} options - Export configuration options.
 * @param {string} [options.academicYear] - Academic year filter applied.
 * @param {string} [options.generatedBy] - Full name of the exporting instructor/admin.
 * @param {Object} [options.filtersSummary] - Key-value map of applied filters.
 * @param {Object} [options.summaryMetrics] - KPI summary numbers.
 * @param {string} [options.filename] - Custom output filename.
 */
export function exportReportsToCSV(records = [], options = {}) {
  const {
    academicYear = 'All Academic Years',
    generatedBy = 'Authorized CMS Instructor',
    filtersSummary = {},
    summaryMetrics = {},
    filename,
  } = options;

  const now = new Date();
  const timestampIso = now.toISOString();
  const formattedDate = now.toLocaleString('en-US', {
    dateStyle: 'medium',
    timeStyle: 'short',
  });

  // 1. Institutional Audit Header Block
  const headerLines = [
    ['BukSU Capstone Management System — Institutional Analytics & Capstone Report'],
    ['Generated At', formattedDate, `ISO: ${timestampIso}`],
    ['Generated By', generatedBy],
    ['Target Academic Year', academicYear],
    ['Total Records', records.length],
  ];

  if (summaryMetrics.totalCapstones !== undefined) {
    headerLines.push([
      'Summary Metrics',
      `Archived: ${summaryMetrics.totalCapstones || 0}`,
      `Students: ${summaryMetrics.totalStudents || 0}`,
      `Plagiarism Flags: ${summaryMetrics.plagiarismFlags || 0}`,
      `Yield Rate: ${summaryMetrics.yieldRate || 'N/A'}%`,
    ]);
  }

  // Active filters section
  const filterEntries = Object.entries(filtersSummary).filter(
    ([, v]) => v !== undefined && v !== '' && v !== null,
  );
  if (filterEntries.length > 0) {
    headerLines.push([
      'Active Filters Applied',
      filterEntries.map(([k, v]) => `${k}: ${v}`).join(' | '),
    ]);
  }

  // Empty separator line
  headerLines.push([]);

  // 2. Tabular Column Headers
  const columnHeaders = [
    'Project Title',
    'Authors / Proponents',
    'Faculty Adviser',
    'Degree Program',
    'Academic Year',
    'Primary SDG Tag',
    'IT Specialization',
    'Plagiarism Index (%)',
    'Archival Status',
    'Date Archived',
  ];

  // 3. Tabular Row Data
  const dataRows = records.map((record) => {
    const authors = Array.isArray(record.authors)
      ? record.authors
          .map((a) => a.fullName || a.name || `${a.firstName || ''} ${a.lastName || ''}`.trim())
          .join('; ')
      : record.author || '';

    const adviser =
      record.adviser?.fullName ||
      (record.adviserId
        ? `${record.adviserId.firstName || ''} ${record.adviserId.lastName || ''}`.trim()
        : '') ||
      'Unassigned';

    const program = record.course?.label || record.course?.name || record.course?.code || 'BSIT';

    const sdg =
      record.sdgTag ||
      record.sdg ||
      (Array.isArray(record.sdgs) ? record.sdgs.join(', ') : '') ||
      'General / N/A';

    const specialization =
      record.specialization || record.category || record.domain || 'Software Engineering';

    const plagiarismScore =
      record.plagiarismScore !== undefined && record.plagiarismScore !== null
        ? `${record.plagiarismScore}%`
        : 'Passed (<25%)';

    const status = record.status || (record.isArchived ? 'Archived' : 'Active');

    const archivedDate = record.archivedAt
      ? new Date(record.archivedAt).toLocaleDateString('en-US', { dateStyle: 'medium' })
      : record.createdAt
        ? new Date(record.createdAt).toLocaleDateString('en-US', { dateStyle: 'medium' })
        : 'N/A';

    return [
      record.title || 'Untitled Project',
      authors,
      adviser,
      program,
      record.academicYear || academicYear,
      sdg,
      specialization,
      plagiarismScore,
      status,
      archivedDate,
    ];
  });

  // 4. Assemble CSV string with DDE sanitization and cell escaping
  const allRows = [
    ...headerLines.map((row) => row.map(escapeCSVCell).join(',')),
    columnHeaders.map(escapeCSVCell).join(','),
    ...dataRows.map((row) => row.map(escapeCSVCell).join(',')),
  ];

  const csvContent = allRows.join('\r\n');
  const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' }); // Add BOM for Excel UTF-8 support

  const outName = filename || `buksu-capstone-report-${now.toISOString().slice(0, 10)}.csv`;

  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = outName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(link.href);

  return outName;
}
