import env from '../config/env.js';
import AppError from '../utils/AppError.js';
import { HTTP_STATUS } from '@cms/shared';

/**
 * verifyCaptcha middleware — validates a Google reCAPTCHA v2 token
 * on the server side by calling Google's siteverify endpoint.
 *
 * Expects `req.body.captchaToken` to contain the reCAPTCHA response token
 * generated by the client-side widget.
 *
 * In development mode (no secret key configured), the check is skipped
 * so local dev is not blocked.
 *
 * @see https://developers.google.com/recaptcha/docs/verify
 */
const verifyCaptcha = async (req, _res, next) => {
  const secretKey = env.RECAPTCHA_SECRET_KEY;

  // Skip verification if no secret key is configured (dev fallback)
  if (!secretKey) {
    return next();
  }

  const { captchaToken } = req.body;

  if (!captchaToken) {
    return next(
      new AppError('Please complete the reCAPTCHA verification.', HTTP_STATUS.BAD_REQUEST),
    );
  }

  try {
    const response = await fetch(
      `https://www.google.com/recaptcha/api/siteverify?secret=${encodeURIComponent(secretKey)}&response=${encodeURIComponent(captchaToken)}`,
      { method: 'POST' },
    );

    const data = await response.json();

    if (!data.success) {
      return next(
        new AppError('reCAPTCHA verification failed. Please try again.', HTTP_STATUS.BAD_REQUEST),
      );
    }

    // Remove captchaToken from body so downstream handlers don't receive it
    delete req.body.captchaToken;

    return next();
  } catch (error) {
    // If the Google API is unreachable, fail open in dev, fail closed in prod
    if (env.isDevelopment) {
      delete req.body.captchaToken;
      return next();
    }

    return next(
      new AppError(
        'reCAPTCHA verification service unavailable. Please try again later.',
        HTTP_STATUS.SERVICE_UNAVAILABLE,
      ),
    );
  }
};

export default verifyCaptcha;
